inputs: 
  document_type:
   - Certificate of Origin
   - Commercial Invoice
   - Proof of Payment
   - Contract
   - Bill of Lading
   - Delivery Note
   - Packing List
   - Customs Clearance
   - Business License
  supporting_channels: 
    - email
    - whatsapp
    - wechat
  sample_record:
    {'Order': 'unqiue combination of string or numbers or both: alpha_test_1',
    'Target Email': 'email address: testing@lifung.com',
    'Target Whatsapp': 'phone number: 85223445688',
    # 'Target Wechat': 'wechat id: testwechat',
    'Status': 'status of the submission: Document Required',
    'Document': 'documnet type: Bill of Lading',
    'Due Date': 'due date: 11/06/2024',
    'Document ID': 'a unique identifier representing the document',
    'Extracted Fields': 'key content extracted from the document'}
  sample_log:
    {'event_type': 'one of the following: reminder/notification/document validation/field extraction',
    'order_id': 'unique indentifer of the order',
    'activity': 'description of the action or event that has occurred',
    'created_time': 'the time of creation of the log'}
  database_keys:
    - Order
    - Target Email
    - Target Whatsapp
    - Status
    - Document
    - Due Date
    - Document ID
    - Extracted Fields
  admin_id:
    - iamadmin
  country_code:
    {"Hong Kong 🇭🇰": "852",
    "China 🇨🇳": "61",
    "India 🇮🇳": "91",
    "Vietnam 🇻🇳": "84",
    "United States 🇺🇸": "1"}
  document status:
    - Document Required
    - AI Validated
    - Human Validated
    - Approved
  doc_type_family:
    {"Certificate of Origin": ["Certificate of Origin"],
    "Commercial Invoice": ["Commercial Invoice", "VAT Invoice", "Invoice"],
    "Proof of Payment": ["Proof of Payment", "Payment Voucher", "Customer Advice", "Bank Transaction Detail", "Detail of Payment"],
    "Contract": ["Contract", "Sales Contract", "Labor Cost Contract", "Purchase Contract"],
    "Bill of Lading": ["Bill of Lading", "Cargo Receipt", "Forwarder Certificate of Receipt"],
    "Delivery Note": ["Delivery Note", "Delivery Challan"],
    "Packing List": ["Packing List"],
    "Customs Clearance": ["Custom Clearance", "Bill of Entry"],
    "Business License": ["Business License", "Trade License", "Business Registration", "Certificate of Registration", "Certificate of Business Registration", "Trademark Registration Certificate"]}
  selected_fields:
    {"Certificate of Origin": ["Document Number", "Shipper Name", "Shipper Address", "Consignee Name", "Consignee Address", "Notify Party", "Port of Loading", "Port of Discharge", "'Details': as dictionaries with (Description of Goods, UOM, Quantity)"],
    "Commercial Invoice": ["Invoice number", "Seller Name", "Seller Address", "Buyer Name", "Buyer Address", "'Details': as dictionaries with (Description of Goods, UOM, Quantity)"],
    "Proof of Payment": ["Payment Reference Number", "Date of Payment", "Payer Name", "Payer Address", "Payee Name", "Payee Address", "Transaction ID"],
    "Contract": ["Contract Number", "Seller Name", "Seller Address", "Buyer Name", "Buyer Address", "Contract Date", "'Details': as dictionaries with (Description of Goods, UOM, Quantity)"],
    "Bill of Lading": ["Document Number", "Shipper Name", "Shipper Address", "Consignee Name", "Consignee Address", "Notify Party", "Port of Loading", "Port of Discharge", "On Board Date", "Cargo Receipt Date", "'Details': as dictionaries with (Description of Goods, UOM, Quantity) refer to attach list for details if necessary"],
    "Delivery Note": ["Delivery Note Number", "Date", "Buyer Name", "Buyer Address", "Supplier Name", "Supplier Address", "Recipient Information", "'Details': as dictionaries with (Description of Goods, UOM, Quantity)", "Quantity Delivered", "'Receipt Confirmation': return (Yes) if signature or stamp spotted else (No)"],
    "Packing List": ["Consignee Name", "Consignee Address", "Consignor Name", "Consignor Address", "Total Number of Carton", "Total Quantity", "Total Gross Weight", "Total Net Weight", "'Details': as dictionaries with (Item Number, Item Description, Item Quantity, Item Carton, Item Gross Weight, Item Net Weight, Item UOM)"],
    "Customs Clearance": ["Customs Number", "Contract Number", "Consignee Name", "Consignee Address", "Consignor Name", "Consignor Address", "User Name", "User Address", "Date", "Gross Weight", "Net Weight", "Origin", "'Details': as dictionaries with (Description of Goods, UOM, Quantity)"],
    "Business License": ["License Number", "Business Name", "Nature of Business", "Business Address", "Commencement Date"]}
database:
  type: mongodb
  db_name: postoffice
  collection: chase_order
tools:
  admin_tools:
  - send_reminder_to_all
  - run_doc_validation
  - web_search
  # - retrieve_from_mongo
  - send_reminder_to_single
  # - add_to_mongo
  # - extract_content_tool
  - retrieve_from_eventlog
  # - research_company_air8
  - validate_and_extract_docs_air8
  - run_document_checker_air8
  - retrieve_information_air8
  - search_company_info_and_news_air8
  - supplier_search
  client_tools:
  - web_search
  - send_reminder_to_single
  # - retrieve_from_mongo
