country_mapping:
  {"General 🇺🇳": "General",
  "China 🇨🇳": "China",
  "India 🇮🇳": "India",}
possible_doc_type:
  - Invoice
  - Purchase Order
  - Delivery Document
General:
  Invoice:
    doc_family:
    - Inovice
    key_fields:
    - Supplier
    - Consignee
    - Consignee Address 
    - Inovice Number
    - Purchase Order Number
    - "'Invoice Date': YYYY/MM/DD"
    - Incoterm
    - "'Payment Terms': also known as Payment Tenor, return the number of days only"
    - "'Details': as dictionaries with (Description of Goods, Quantity, Unit Cost)"
    - Currency
    - Total Price Amount
    - "'Bank Details': as dictionaries with (Account Name, Bank Name, Currency, Account Number, Swift Code)" 
  Purchase Order:
    doc_family:
    - Purchase Request
    - Purchase Order
    key_fields:
    - Supplier
    - "'Consignee': The name of company"
    - Consignee Address
    - "'Purchase Order Number': also known as Import PO #"
    - "'Date': YYYY/MM/DD"
    - Incoterm
    - "'Payment Terms': also known as Payment Tenor, return the number of days only"
    - "'Details': as dictionaries with (Description of Goods, Quantity, Unit Cost)"
    - Delivery Address
    - "'Shipment Date': YYYY/MM/DD"
    - Total Quantity 
    - Total Number of Package
  Delivery Document:
    doc_family:
    - Bill of Lading
    - Forwarder Cargo Receipt
    - Cargo Receipt
    - Delivery Note
    - Delivery Challan
    key_fields:
    - Supplier
    - Consignee
    - Delivery Address
    - "'Date': YYYY/MM/DD"
    - "'Shipment Date': YYYY/MM/DD"
    - Port of Loading
    - Port of Discharge
    - Port of Delivery
    - Vessel
    - "'Details': as dictionaries with (Purchase Order Number, Inovice Number, Invoice Date: YYYY/MM/DD, Description of Goods, Number of Package, Quantity)"
    - Total Quantity
    - Total Number of Package
China:
  Articles of Association:
    doc_family:
    - Articles of Association
    - Memorandum of Association
    key_fields: []
  Bank Statement:
    doc_family:
    - Bank Account Statement
    - Bank Receipt
    - Online Banking Receipt
    - Online Banking Account Statment
    - Bank Transaction Receipt
    key_fields:
    - Account Number
    - "'Date': YYYY/MM/DD"
    - Company Name
    - Bank Name
    - Branch Name
    - Branch Address
  Business License:
    doc_family:
    - Business License
    - Business Registration
    key_fields:
    - License Number
    - Business Name
    - Nature of Business
    - Business Address
    - "'Commencement Date': YYYY/MM/DD"
  ID Card:
    doc_family:
    - ID Card
    key_fields:
    - Name
    - ID Number
    - "'Beginning Date': YYYY/MM/DD"
    - "'Expiry Date': YYYY/MM/DD"
  List of Board Members:
    doc_family:
    - List of Board Members
    - List of Executive Directors
    key_fields:
    - Company Name
    - "'Date': YYYY/MM/DD"
    - Enterprise Trade Foreign Exchange Income and Expenditure Directory for Goods
      Trade Classification
  Shareholding Structure Diagram:
    doc_family:
    - Shareholding Structure Diagram
    - Table of Shareholding
    key_fields:
    - Company Name
    - "'Date': YYYY/MM/DD"
    - 'Shareholders: as a dicitonary (Name, Number of Share, Share of Holding in %)'
  Statement of the State Administration of Foreign Exchange:
    doc_family:
    - Statement of the State Administration of Foreign Exchange
    - Statement of SAFE
    key_fields:
    - Company Name
    - "'Date': YYYY/MM/DD"
    - The Enterprise's Trade Foreign Exchange Receipts and Payments for Goods Trade under the Supplier's Directory
India:
  Articles of Association:
    doc_family:
    - Articles of Association
    - Memorandum of Association
    key_fields: []
  Bank Statement:
    doc_family:
    - Bank Account Statement
    - Bank Receipt
    - Online Banking Receipt
    - Online Banking Account Statment
    - Bank Transaction Receipt
    key_fields:
    - Account Number
    - "'Date': YYYY/MM/DD"
    - Company Name
    - Bank Name
    - Currency
  Certificate of Incorporation:
    doc_family:
    - Certificate of Incorporation
    - Incorporation Certificate
    key_fields:
    - Registration Number
    - Company Name
    - "'Date': YYYY/MM/DD"
  GST Certificate:
    doc_family:
    - GST Certificate
    key_fields:
    - Registration Number
    - Legal Name
    - Constitution of Business
    - Address
    - "'Date of Liability': YYYY/MM/DD"
    - "'Date of Validity': YYYY/MM/DD"
    - "'Date of Issue': YYYY/MM/DD"
    - "'Key Persons': as a dicitonary (Name, Designation, Resident of State)"
  Importer-Exporter Code Certificate:
    doc_family:
    - Importer-Exporter Code Certificate
    - IEC Certificate
    - Certificate of IEC
    key_fields:
    - IEC
    - PAN
    - Company Name
    - Nature of Concern
    - Address
    - "'Date of Issue': YYYY/MM/DD"
    - Name of Signatory
  National ID:
    doc_family:
    - National ID
    - ID Card
    key_fields:
    - Enrolment Number
    - Aadhaar Number
    - Name
    - Address
  PAN Card:
    doc_family:
    - PAN Card
    - Permanent Account Number
    key_fields:
    - Permanent Account Number
    - Name
    - "'Date': YYYY/MM/DD"
  Shareholding Structure Diagram:
    doc_family:
    - Shareholding Structure Diagram
    - Organisation Chart
    - Table of Shareholding
    key_fields:
    - Company Name
    - "'Date': YYYY/MM/DD"
    - "'Shareholders': as a dicitonary (Name, Number of Share, Share of Holding in %)"
check_rules:
  - 1. Compare the supplier name.
  - 2. Compare the buyer name.
  - 3. Compare the purchase order number.
  - 4. Compare the invoice number of invoice and the delivery document.
  - 5. Verify the issue date of the purchase order is earlier than the dates on the invoice and delivery document.
  - 6. Check whether the invoice date is after purchase order date and not more than 30 days from shipment date of delivery note.
  - 7. Compare the payment terms and tenor of purchase order and invoice.
  - 8. Compare the delivery address of purchase order and delivery document.
  - 9. Check the total price amount equals to unit cost multiplied by the quantity listed in the invoice.
  - 10. Compare the shipment date of purchase order and of delivery document.
  - 11. Verify Air8 account details are in the bank details.
  - 12. Compare the quantity of product in the invoice and delivery document under the same invoice number.
  - 13. Check the total quantity on delivery document is within plus or minus 5% of the total quantity of purchase order.
tools:
  admin_tools:
  - web_search
  - research_company_air8
  - validate_and_extract_docs_air8
  - run_document_checker_air8
  - retrieve_information_air8
  - search_company_info_and_news_air8
  client_tools:
  - web_search
  - retrieve_information_air8
database:
  mongodb:
    db_name: postoffice
  blob_storage:
    db_name: air8-documents
  validate_n_extract:
    in:
      db_name: druid-config-test
      collection: field_configs
    out:
      db_name: druid-execution-test
      collection: extraction_executions
  content_checker:
    in:
      db_name: druid-config-test
      collection: checker_configs
    out:
      db_name: druid-execution-test
      collection: check_content_executions
